language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: BF7qkQ4jkCTVkSZm5AfwKaHPJGMcx31SlHU+1Ay9oi6peyBT1QCetF7hCh/+lyZze6DEUooTJJHctwN5zWYIUfBoecrtTRD/lf33yrS0CzbmUaYVg8oaoM0V46448HLiKmI2t001wiEP28QJmbn0i5L6FO/B4eV0f8aEkTXKNRA=
